ZSH=$HOME/.oh-my-zsh
ZSH_THEME="avit"
DISABLE_CORRECTION="true"
plugins=(docker gradle lein bundler git git-extras rake autojump rvm vagrant \ 
  rails history debian history-substring-search \
  zsh-autosuggestions command-not-found svn-fast-info) 

source $ZSH/oh-my-zsh.sh

## antigen
source $STU_HOME/tools/antigen/antigen.zsh

# Vi-mode
# antigen bundle vi-mode # Only for prompt
# antigen bundle sharat87/zsh-vim-mode
bindkey "^R" history-incremental-search-backward
bindkey "^F" forward-char # Make them work in vicmd
bindkey "^D" delete-char-or-list

if (type antigen | grep -e 'function' > /dev/null); then
  # antigen bundle sharat87/autoenv
  antigen bundle zsh-users/zsh-syntax-highlighting 

  antigen bundle gmatheu/shell-plugins explain-shell
  antigen bundle gmatheu/shell-plugins dirrc
  antigen bundle gmatheu/shell-plugins docker
  antigen bundle gmatheu/shell-plugins notify
  antigen bundle gmatheu/shell-plugins git
  antigen bundle gmatheu/shell-plugins git-svn 
  antigen bundle gmatheu/shell-plugins vim
  antigen bundle gmatheu/shell-plugins svn
  antigen bundle gmatheu/shell-plugins virtualbox

  antigen theme avit 

  antigen apply
fi

# Customize to your needs...
export PATH=$PATH:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

source ~/.profile

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
