ZSH=$HOME/.oh-my-zsh
ZSH_THEME="avit"
DISABLE_CORRECTION="true"
plugins=(docker gradle lein bundler git git-extras rake autojump rvm vagrant \ 
  rails history debian zsh-syntax-highlighting history-substring-search \
  zsh-autosuggestions zsh-explain-shell command-not-found)

source $ZSH/oh-my-zsh.sh

## antigen
source $STU_HOME/tools/antigen/antigen.zsh

# Vi-mode
antigen bundle vi-mode # Only for prompt
antigen bundle sharat87/zsh-vim-mode
bindkey "^R" history-incremental-search-backward
bindkey "^F" forward-char # Make them work in vicmd
bindkey "^D" delete-char-or-list

antigen bundle gmatheu/shell-plugins explain-shell
antigen bundle gmatheu/shell-plugins dirrc
antigen bundle gmatheu/shell-plugins docker
antigen bundle gmatheu/shell-plugins notify
antigen bundle gmatheu/shell-plugins git
antigen bundle gmatheu/shell-plugins vim
antigen apply

# Customize to your needs...
export PATH=$PATH:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

source ~/.profile

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
